name: ci

on: 
  push:
    branches: ["main"]

jobs:
  replace: 
    name: replace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout step
        uses: actions/checkout@v4
      - name: Replace step
        run: sed -i 's/SECRET/ultra-secret/g' myFile/env.ts
      - name: "Read file contents"
        uses: andstor/file-reader-action@v1
        with:
          path: "./myFile/env.ts"
            
